---
# groups are 45: Onwers_Manual, 136: Owners (auto), 107: FormerOwners (expired)
:ownership:
  :settings:
    :all_ownership_group_ids:
    - 45
    - 136
  :manual:
    :new_user_found:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: NU
      :days_until_renews: 9999
      :action_sequence: R0
      :add_to_group: 108
      :message_to: 
      :message_cc: KM_Admin
      :message_from: Kim_Miller
      :excludes: []
    :new_user_one_week_ago:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: NU
      :days_until_renews: -7
      :action_sequence: R1
      :add_to_group: 
      :remove_from_group: 
      :message_from: Kim_Miller
      :excludes: []
    :new_user_two_weeks_ago:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: NU
      :days_until_renews: -14
      :action_sequence: R2
      :add_to_group: 
      :remove_from_group: 
      :message_from: Kim_Miller
      :excludes: []
    :new_user_three_weeks_ago:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: NU
      :days_until_renews: -21
      :action_sequence: R3
      :message_cc: KM_Admin
      :message_from: Kim_Miller
      :excludes: []
    :scholarship_new_found:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: SM
      :days_until_renews: 9999
      :action_sequence: R0
      :add_to_group: 45
      :remove_from_group: 107
      :message_to: 
      :message_cc: KM_Admin,Mike_Drilling
      :message_from: Kim_Miller
      :excludes: []
    :scholarship_expires_next_week:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: SM
      :days_until_renews: 7
      :action_sequence: R1
      :add_to_group: 
      :remove_from_group: 
      :message_from: Kim_Miller
      :excludes: []
    :scholarship_expired_today:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: SM
      :days_until_renews: 0
      :action_sequence: R2
      :add_to_group: 
      :remove_from_group: 
      :message_from: Kim_Miller
      :excludes: []
    :scholarship_final:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: SM
      :days_until_renews: -7
      :add_to_group: 107
      :remove_from_group: 45
      :action_sequence: R3
      :message_cc: KM_Admin
      :message_from: Kim_Miller
      :excludes: []
    :zelle_new_found:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: ZM
      :days_until_renews: 9999
      :action_sequence: R0
      :add_to_group: 45
      :remove_from_group: 107
      :message_to:
      :message_cc: KM_Admin,Mike_Drilling
      :message_from: Kim_Miller
      :excludes: []
    :zelle_expires_next_week:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: ZM
      :days_until_renews: 7
      :action_sequence: R1
      :add_to_group:
      :remove_from_group:
      :message_from: Kim_Miller
      :excludes: []
    :zelle_expired_today:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: ZM
      :days_until_renews: 0
      :action_sequence: R2
      :add_to_group:
      :remove_from_group:
      :message_from: Kim_Miller
      :excludes: []
    :zelle_final:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: ZM
      :days_until_renews: -7
      :add_to_group: 107
      :remove_from_group: 45
      :action_sequence: R3
      :message_cc: KM_Admin
      :message_from: Kim_Miller
      :excludes: []
    :memberful_expires_next_week:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: MM
      :days_until_renews: 7
      :action_sequence: R1
      :add_to_group: 
      :remove_from_group: 
      :message_cc: 
      :message_from: Kim_Miller
      :excludes: []
    :memberful_expired_today:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: MM
      :days_until_renews: 0
      :action_sequence: R2
      :add_to_group: 
      :remove_from_group: 
      :message_cc: KM_Admin
      :message_from: Kim_Miller
      :excludes: []
    :memberful_final:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: MM
      :days_until_renews: -7
      :add_to_group: 107
      :remove_from_group: 45
      :action_sequence: R3
      :message_cc: KM_Admin,Mike_Drilling
      :message_from: Kim_Miller
      :excludes: []
  :auto:
    :card_auto_renew_new_subscription_found:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: CA
      :days_until_renews: 9999
      :action_sequence: R0
      :add_to_group: 
      :remove_from_group: 107
      :message_to: 
      :message_cc: KM_Admin,Mike_Drilling
      :message_from: Kim_Miller
      :subscrption_name: Owner Auto Renewing
      :excludes: []
    :card_auto_renew_expires_next_week:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: CA
      :days_until_renews: 7
      :action_sequence: R1
      :add_to_group: 
      :remove_from_group: 
      :message_from: Kim_Miller
      :subscrption_name: Owner Auto Renewing
      :excludes: []
    :card_auto_renew_expired_yesterday:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: CA
      :days_until_renews: -1
      :action_sequence: R2
      :add_to_group: 
      :remove_from_group: 
      :message_from: Kim_Miller
      :excludes: []
    :card_auto_renew_expired_last_week_final:
      :do_task_update: true
      :user_fields: '6'
      :ownership_code: CA
      :days_until_renews: -7
      :action_sequence: R3
      :add_to_group: 107
      :remove_from_group: 136
      :message_cc: KM_Admin,Mike_Drilling
      :message_from: Kim_Miller
      :excludes: []

:category:
  :matching_team:
    :do_task_update: true
    :allowed_levels:
    - 3
    :set_level: 3
    :excludes:
    - Steve_Scott
    - Ryan_Hyer
    - David_Kirk
  :Essential:
    :do_task_update: true
    :allowed_levels:
    - 3
    :set_level: 3
    :excludes:
    - Steve_Scott
    - Joe_Sabolefski
  :Growth:
    :do_task_update: true
    :allowed_levels:
    - 3
    - 4
    :set_level: 4
    :excludes:
    - Joe_Sabolefski
    - Bill_Herndon
    - Michael_Wilson
    - Howard_Bailey
    - Steve_Scott
    - Suhas_Chelian
  :Meta:
    :do_task_update: true
    :allowed_levels:
    - 3
    - 4
    :set_level: 4
    :excludes:
    - Joe_Sabolefski
    - Bill_Herndon
    - Michael_Wilson
    - Howard_Bailey
    - Steve_Scott
:group:
  :group_alias:
    :do_task_update: true
    :allowed_levels: 
    :set_level: 
    :excludes: []
:user:
  :preferences:
    :user_option:
      :email_messages_level:
        :do_task_update: true
        :allowed_levels: 0
        :set_level: 0
        :excludes:
        - Steve_Scott
        - David_Kirk
  :downgrade_non_owner_trust:
    :do_task_update: true
    :allowed_levels: 0
    :set_level: 0
    :excludes: []
  :activity_groupping:
    :active_user:
      :do_task_update: true
      :allowed_levels: 130
      :set_level: 130
      :excludes: []
    :average_user:
      :do_task_update: true
      :allowed_levels: 133
      :set_level: 133
      :excludes: []
    :email_user:
      :do_task_update: true
      :allowed_levels: 131
      :set_level: 131
      :excludes: []
    :inactive_user:
      :do_task_update: true
      :allowed_levels: 132
      :set_level: 132
      :excludes: []

:user_scores:
  :update_type: newly_voted
  :target_post: 30719
  :poll_url: https://discourse.gomomentum.org/t/what-s-your-score/7104
  :messages_from: Kim_Miller
  :excludes: []
